/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._portal;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _activity_0list__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_5.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/portal/activity_list.jsp"), 99962262154112592L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${appId}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${timestamp}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${noncestr}");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${signature}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;

  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  static {
    _jsp_string3 = "/phone-css/phone.css\" rel=\"stylesheet\">\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string5 = "', // \u5fc5\u586b\uff0c\u516c\u4f17\u53f7\u7684\u552f\u4e00\u6807\u8bc6\r\n             timestamp: '".toCharArray();
    _jsp_string6 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u65f6\u95f4\u6233\r\n             nonceStr: '".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n		<title>\u5199\u65e5\u5fd7\u8d62\u62cd\u7acb\u5f97\u76f8\u673a</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n  		<link href=\"".toCharArray();
    _jsp_string7 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u968f\u673a\u4e32\r\n             signature:'".toCharArray();
    _jsp_string9 = "/images/public_code.jpg\" id=\"publicCode\" width=\"80px\" alt=\"\" />\r\n		\u5173\u6ce8\u516c\u4f17\u53f7\r\n	</div>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string8 = "',// \u5fc5\u586b\uff0c\u7b7e\u540d\r\n             jsApiList: ['checkJsApi',\r\n                         'previewImage'] // \u5fc5\u586b\uff0c\u9700\u8981\u4f7f\u7528\u7684JS\u63a5\u53e3\u5217\u8868\r\n         });\r\n    	 wx.ready(function(){ \r\n			 $(\"#publicCode\").click(function(e){\r\n				 wx.previewImage({\r\n	                 current: this.src,\r\n	                 urls: [this.src]\r\n	             });\r\n			 });\r\n		 });\r\n    	</script>\r\n</head>\r\n<body>\r\n	<div class=\"activity-box\">\r\n		<div class=\"activity-rolue-box\">\r\n			<ul>\r\n				<li>1\u3001\u5373\u65e5\u8d77\u81f32018\u5e7410\u670810\u65e5\u83b7\u5f97\u70b9\u8d5e\u6570\u6700\u591a\u7684\u65e5\u5fd7\u4f5c\u8005\u5c06\u83b7\u5f97\u7531\u672c\u516c\u4f17\u53f7\u63d0\u4f9b\u7684\u62cd\u7acb\u5f97\u4e00\u53f0</li>\r\n				<li>2\u3001\u6d3b\u52a8\u671f\u95f4\u5927\u5bb6\u53ef\u4ee5\u70b9\u51fb\u83dc\u5355\u680f\u91cc\u7684\u201c\u6392\u884c\u699c\u201d\u968f\u65f6\u5173\u6ce8\u65e5\u5fd7\u7684\u70b9\u8d5e\u6392\u540d\u60c5\u51b5</li>\r\n				<li>3\u3001\u6d3b\u52a8\u7ed3\u675f\u540e\u4f1a\u5728\u6b64\u5904\u516c\u5e03\u83b7\u5956\u8005\uff0c\u83b7\u5956\u8005\u9700\u5728\u4e00\u5468\u5185\u5728\u201c\u6211\u7684\u8d26\u6237\u201d\u91cc\u586b\u5199\u5177\u4f53\u6536\u8d27\u4fe1\u606f</li>\r\n				<li>4\u3001\u83b7\u5956\u8005\u63d0\u4ea4\u5b8c\u6536\u8d27\u4fe1\u606f\u540e\u5ba2\u670d\u4eba\u5458\u4f1a\u786e\u8ba4\u4fe1\u606f\uff0c\u786e\u8ba4\u65e0\u8bef\u540e\u4f1a\u5728\u4e00\u5468\u5185\u5bc4\u51fa</li>\r\n				<li>5\u3001\u83b7\u5956\u8005\u6536\u5230\u5956\u54c1\u540e\u9700\u4e0a\u4f20\u7167\u7247\u53ca\u83b7\u5956\u611f\u8a00\uff0c\u5426\u5219\u4f1a\u5f71\u54cd\u4eca\u540e\u7684\u6d3b\u52a8\u7684\u53c2\u4e0e</li>\r\n			</ul>\r\n		</div>\r\n	</div>\r\n	<div class=\"public-intro-box\" >\r\n		<img src=\"".toCharArray();
    _jsp_string4 = "/js/jquery.js\"></script>\r\n		<script type=\"text/javascript\" src=\"http://res.wx.qq.com/open/js/jweixin-1.2.0.js\"></script>\r\n    	<script type=\"text/javascript\">\r\n    	 wx.config({\r\n             debug: false, // \u5f00\u542f\u8c03\u8bd5\u6a21\u5f0f,\u8c03\u7528\u7684\u6240\u6709api\u7684\u8fd4\u56de\u503c\u4f1a\u5728\u5ba2\u6237\u7aefalert\u51fa\u6765\uff0c\u82e5\u8981\u67e5\u770b\u4f20\u5165\u7684\u53c2\u6570\uff0c\u53ef\u4ee5\u5728pc\u7aef\u6253\u5f00\uff0c\u53c2\u6570\u4fe1\u606f\u4f1a\u901a\u8fc7log\u6253\u51fa\uff0c\u4ec5\u5728pc\u7aef\u65f6\u624d\u4f1a\u6253\u5370\u3002\r\n             appId: '".toCharArray();
  }
}
