/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._portal;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _integral_0mall__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string11, 0, _jsp_string11.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    _caucho_expr_5.print(out, _jsp_env, false);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    _caucho_expr_6.print(out, _jsp_env, false);
    out.write(_jsp_string14, 0, _jsp_string14.length);
    _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_2 = _caucho_expr_7.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
    _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
    Object _jsp_status_2 = pageContext.putAttribute("status", _jsp_loop_1);
    while (_jsp_iter_2.hasNext()) {
      Object _jsp_i_2 = _jsp_iter_2.next();
      _jsp_loop_1.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
      pageContext.setAttribute("a", _jsp_i_2);
      out.write(_jsp_string15, 0, _jsp_string15.length);
      _caucho_expr_8.print(out, _jsp_env, false);
      out.write(_jsp_string16, 0, _jsp_string16.length);
      _caucho_expr_9.print(out, _jsp_env, false);
      out.write(_jsp_string17, 0, _jsp_string17.length);
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write(_jsp_string18, 0, _jsp_string18.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string19, 0, _jsp_string19.length);
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write('/');
      _caucho_expr_11.print(out, _jsp_env, false);
      out.write(_jsp_string20, 0, _jsp_string20.length);
      _caucho_expr_9.print(out, _jsp_env, false);
      out.write(_jsp_string21, 0, _jsp_string21.length);
      _caucho_expr_12.print(out, _jsp_env, false);
      out.write(_jsp_string22, 0, _jsp_string22.length);
      _caucho_expr_13.print(out, _jsp_env, false);
      out.write(_jsp_string23, 0, _jsp_string23.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string24, 0, _jsp_string24.length);
    }
    pageContext.pageSetOrRemove("a", null);
    if (_jsp_status_2 instanceof javax.servlet.jsp.jstl.core.LoopTagStatus)pageContext.pageSetOrRemove("status", _jsp_status_2);
    else
      pageContext.pageSetOrRemove("status", null);
    out.write(_jsp_string25, 0, _jsp_string25.length);
    _caucho_expr_9.print(out, _jsp_env, false);
    out.write(_jsp_string26, 0, _jsp_string26.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string27, 0, _jsp_string27.length);
    _caucho_expr_9.print(out, _jsp_env, false);
    out.write(_jsp_string28, 0, _jsp_string28.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/portal/integral_mall.jsp"), 5203901305670402573L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1;

    final com.caucho.jsp.IteratorLoopSupportTag get_jsp_loop_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_loop_1 == null) {
        _jsp_loop_1 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_loop_1;
    }

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${appId}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${timestamp}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${noncestr}");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${signature}");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${lastIdSign }");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${awardList }");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${(status.index+1)%2==0?'rightLi':'leftLi' }");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${a.id }");
      _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${a.cover}");
      _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${a.integral_need }");
      _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${a.inventory }");
      _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${a.description }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;

  private final static char []_jsp_string3;
  private final static char []_jsp_string23;
  private final static char []_jsp_string9;
  private final static char []_jsp_string17;
  private final static char []_jsp_string14;
  private final static char []_jsp_string2;
  private final static char []_jsp_string24;
  private final static char []_jsp_string21;
  private final static char []_jsp_string10;
  private final static char []_jsp_string11;
  private final static char []_jsp_string19;
  private final static char []_jsp_string15;
  private final static char []_jsp_string6;
  private final static char []_jsp_string18;
  private final static char []_jsp_string0;
  private final static char []_jsp_string26;
  private final static char []_jsp_string20;
  private final static char []_jsp_string28;
  private final static char []_jsp_string8;
  private final static char []_jsp_string13;
  private final static char []_jsp_string12;
  private final static char []_jsp_string25;
  private final static char []_jsp_string1;
  private final static char []_jsp_string27;
  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string22;
  private final static char []_jsp_string16;
  static {
    _jsp_string3 = "/phone-css/reset.css\" />\r\n		<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string23 = "</span>\r\n							</p>\r\n							<p class=\"index-diary-content\">".toCharArray();
    _jsp_string9 = "/phone-js/xback.js\"></script>\r\n		<script type=\"text/javascript\" src=\"http://res.wx.qq.com/open/js/jweixin-1.2.0.js\"></script>\r\n		<script type=\"text/javascript\" >\r\n		XBack.listen(function(){\r\n	 		wx.closeWindow();\r\n		});\r\n		 wx.config({\r\n			 debug: false, // \u5f00\u542f\u8c03\u8bd5\u6a21\u5f0f,\u8c03\u7528\u7684\u6240\u6709api\u7684\u8fd4\u56de\u503c\u4f1a\u5728\u5ba2\u6237\u7aefalert\u51fa\u6765\uff0c\u82e5\u8981\u67e5\u770b\u4f20\u5165\u7684\u53c2\u6570\uff0c\u53ef\u4ee5\u5728pc\u7aef\u6253\u5f00\uff0c\u53c2\u6570\u4fe1\u606f\u4f1a\u901a\u8fc7log\u6253\u51fa\uff0c\u4ec5\u5728pc\u7aef\u65f6\u624d\u4f1a\u6253\u5370\u3002\r\n             appId: '".toCharArray();
    _jsp_string17 = "/portal/integral!awardDetail.action?award.id=".toCharArray();
    _jsp_string14 = "\"/>\r\n		<div id=\"wrapper\">\r\n			<ul id=\"ulId\">\r\n				".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n	<head>\r\n		<title>\u79ef\u5206\u5546\u57ce</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;\">\r\n		<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n		<meta name=\"format-detection\" content=\"telephone=no\">\r\n		<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string24 = "</p>\r\n							<span style=\"float:right;margin-top:5px;\">\u2026\u2026</span>\r\n							<div class=\"clear\" ></div>\r\n						</div>\r\n					</li>\r\n				".toCharArray();
    _jsp_string21 = "/images/default_diary_image.jpg'\"  style=\"width:100%;height:200px;\"/>\r\n						</figure>\r\n						<div class=\"index-diary-detail\">\r\n							<p class=\"index-diary-title\" >\r\n								<span style=\"color:red;\">".toCharArray();
    _jsp_string10 = "', // \u5fc5\u586b\uff0c\u516c\u4f17\u53f7\u7684\u552f\u4e00\u6807\u8bc6\r\n             timestamp: '".toCharArray();
    _jsp_string11 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u65f6\u95f4\u6233\r\n             nonceStr: '".toCharArray();
    _jsp_string19 = "/awardImages/award".toCharArray();
    _jsp_string15 = "\r\n					<li class=\"".toCharArray();
    _jsp_string6 = "/phone-js/iscroll.js\"></script>\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string18 = "'\">\r\n						<figure style=\"display:block;float:left;margin:0 5px 5px 0;width:100%;\">\r\n							<img src=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string26 = "/portal/integral!mall.action';\r\n				}\r\n				\r\n				function Load() {\r\n					loadData();\r\n					setTimeout(function () {// <-- Simulate network congestion, remove setTimeout from production!\r\n						var el, li, i;\r\n						el = document.querySelector(\"#wrapper ul\");\r\n						if(loadDatas != ''){\r\n							var clearNode = document.getElementById('clearDiv');\r\n							clearNode.parentNode.removeChild(clearNode);\r\n							var liList = document.getElementsByName('awardLi');\r\n							var floatSign = 0;\r\n							if(liList.length>0){\r\n								var lastLi = liList[liList.length-1];\r\n								var floatVal = lastLi.style.float;\r\n								if(floatVal == 'left'){\r\n									floatSign = 4;\r\n								}else {\r\n									floatSign = 3;\r\n								}\r\n							}\r\n							$.each(loadDatas,function(i,item){\r\n								li = document.createElement('li');\r\n								li.className = 'mui-table-view-cell';\r\n								li.setAttribute('name','awardLi');\r\n								li.setAttribute('id','awardLi'+item.id);\r\n								 if(floatSign%2 == 0){\r\n									li.className = 'rightLi';\r\n								}else {\r\n									li.className = 'leftLi';\r\n								} \r\n								floatSign = floatSign + 1;\r\n								li.innerHTML = '<figure style=\"display:block;float:left;margin:0 5px 5px 0;width:100%;\">'\r\n										     		+ '<img src=\"".toCharArray();
    _jsp_string20 = "\" \r\n								onerror=\"src='".toCharArray();
    _jsp_string28 = "/portal/integral!awardDetail.action?award.id='+item.id;\r\n								};\r\n								if(i == loadDatas.length-1){\r\n									var lastIdSignNode = document.getElementById('lastIdSign');\r\n									lastIdSignNode.value = item.id;\r\n								}\r\n								el.appendChild(li, el.childNodes[0]);\r\n				    		});\r\n						}\r\n						wrapper.refresh();/****remember to refresh after action completed\uff01\uff01\uff01   ---id.refresh(); --- ****/\r\n						for (var i = 0; i < document.querySelectorAll(\"#wrapper ul li\").length; i++) {\r\n							document.querySelectorAll(\"#wrapper ul li\")[i];\r\n						}\r\n						var ulNode = document.getElementById('ulId');\r\n						var newClearDiv = document.createElement('div');\r\n						newClearDiv.className = 'clear';\r\n						newClearDiv.id = 'clearDiv';\r\n						ulNode.appendChild(newClearDiv);\r\n						loadDatas = '';\r\n					}, 1000);\r\n				}\r\n				\r\n		</script>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string8 = "/js/jquery.js\"></script>\r\n		<script type=\"text/javascript\"  src=\"".toCharArray();
    _jsp_string13 = "',// \u5fc5\u586b\uff0c\u7b7e\u540d\uff0c\u89c1\u9644\u5f551\r\n			      jsApiList: [\r\n			                  'checkJsApi'\r\n			                 ] // \u5fc5\u586b\uff0c\u9700\u8981\u4f7f\u7528\u7684JS\u63a5\u53e3\u5217\u8868\uff0c\u6240\u6709JS\u63a5\u53e3\u5217\u8868\u89c1\u9644\u5f552\r\n			      });\r\n		</script>\r\n		<style type='text/css'>\r\n			.leftLi{\r\n				float:left;\r\n				margin-left:2.5%;\r\n			}\r\n			.rightLi {\r\n				float:right;\r\n				margin-right:2.5%;\r\n			}\r\n		</style>\r\n	</head>\r\n	<body style=\"background-color:#F0EFEE;\">\r\n		<input type=\"hidden\" id=\"lastIdSign\" value=\"".toCharArray();
    _jsp_string12 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u968f\u673a\u4e32\r\n             signature:'".toCharArray();
    _jsp_string25 = "\r\n				<div class=\"clear\" id=\"clearDiv\"></div>\r\n			</ul>\r\n		</div>\r\n		<script type=\"text/javascript\">\r\n				var loadDatas = \"\";\r\n				var model = $(\"#model\").val();\r\n				function loadData(){\r\n					var	lastIdSign = $(\"#lastIdSign\").val();\r\n					 $.ajax({ \r\n						 type: \"post\", \r\n						 url: \"integral!loadData.action\", \r\n						 async: false,\r\n						 dataType: \"json\", \r\n						 data:{\"lastIdSign\":lastIdSign},\r\n						 success: function (data) {\r\n							 if(data != \"0\"&&data!=\"-1\"){\r\n								 loadDatas = data;\r\n							 }else {\r\n								 loadDatas = \"\";\r\n							 }\r\n						 } \r\n						});\r\n				}\r\n				refresher.init({\r\n					id: \"wrapper\",//<------------------------------------------------------------------------------------\u2510\r\n					pullDownAction: Refresh,\r\n					pullUpAction: Load\r\n				});\r\n				var generatedCount = 0;\r\n				function Refresh() {\r\n					window.location = '".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string27 = "/awardImages/award'+item.id+'/'+item.cover+'\"' \r\n											 		+ ' onerror=\"src=\\'/images/default_diary_image.jpg\\'\"  style=\"width:100%;height:200px;\"/>'\r\n										     + '</figure>'\r\n										     + '<div class=\"index-diary-detail\">'\r\n									         		+ '<p class=\"index-diary-title\" >'\r\n									         				+'<span style=\"color:red;\">'+item.integral_need+'</span>'\r\n									         				+'&nbsp;\u79ef\u5206'\r\n															+'<span style=\"float:right;margin-right:5px;\">\u6570\u91cf\uff1a'+item.inventory+'</span>'\r\n									         		+'</p>'\r\n											 		+ '<p class=\"index-diary-content\">'+item.description+'</p>'\r\n											 		+ '<span style=\"float:right;margin-top:5px;\">\u2026\u2026</span>'\r\n											 		+ '<div class=\"clear\" ></div>'\r\n											 + '</div>';\r\n								li.onclick=function(){\r\n									window.location='".toCharArray();
    _jsp_string4 = "/phone-css/pullToRefresh.css\" />\r\n		<link href=\"".toCharArray();
    _jsp_string7 = "/phone-js/pullToRefresh.js\"></script>\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string5 = "/phone-css/phone.css\" rel='stylesheet' type='text/css' />\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string22 = "</span>\r\n								&nbsp;\u79ef\u5206\r\n								<span style=\"float:right;margin-right:5px;\">\u6570\u91cf\uff1a".toCharArray();
    _jsp_string16 = "\" \r\n						onclick=\"window.location='".toCharArray();
  }
}
