/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._portal;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _user_0login__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/portal/user_login.jsp"), 541039541449283343L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${from }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;

  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  static {
    _jsp_string6 = "/images/phone-login-bg.png) no-repeat;background-size:100% 100%;\">\r\n	<div class=\"login-box\" >\r\n		<form action=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string3 = "/phone-css/phone.css\" rel=\"stylesheet\">\r\n		\r\n			 <script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string7 = "/portal/user!login.action\" method=\"post\" id=\"loginForm\">\r\n			<input type=\"hidden\" name=\"from\" value=\"".toCharArray();
    _jsp_string5 = "/portal/user!imgcode.action?a='+new Date().getTime();\r\n			}\r\n	    	function login(){\r\n	    		$(\"#loginForm\").submit();\r\n	    	}\r\n	    	function forgetPass(){\r\n	    		alert(\"\u8bf7\u53d1\u9001\u5bc6\u7801\u4e24\u4e2a\u6c49\u5b57\u5230\u516c\u4f17\u53f7\u91cd\u65b0\u8bbe\u7f6e\u5bc6\u7801\uff01\");\r\n	    	}\r\n    	</script>\r\n    	<style type=\"text/css\">\r\n    		input{\r\n    			height:25px;\r\n    		}\r\n    	</style>\r\n</head>\r\n<body style=\"width:100%;height:800px;background:url(".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string4 = "/js/jquery.js\"></script>\r\n    	<script type=\"text/javascript\">\r\n	    	function refreshImg()\r\n			{\r\n				document.getElementById(\"codeImg\").src='".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n		<title>\u7528\u6237\u767b\u5f55</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n  		<link href=\"".toCharArray();
    _jsp_string8 = "\"/>\r\n			<table>\r\n				<tr>\r\n					<td >\u767b\u5f55\u540d\uff1a</td>\r\n					<td><input type=\"text\" name=\"user.login_name\" /></td>\r\n				</tr>\r\n				<tr>\r\n					<td>\u5bc6&nbsp;&nbsp;&nbsp;\u7801\uff1a</td>\r\n					<td>\r\n						<input type=\"password\" style=\"width:60%;margin-right:10px;\" name=\"user.password\" />\r\n						<span style=\"color:blue;\" onclick=\"forgetPass()\">\u5fd8\u8bb0\u5bc6\u7801</span>\r\n					</td>\r\n				</tr>\r\n				<!-- <tr>\r\n					<td>\u9a8c\u8bc1\u7801\uff1a</td>\r\n					<td>\r\n						<input type=\"text\" name=\"imgCode\" style=\"width:60px;;\"/>\r\n						<img  style=\"cursor: pointer; height:30px;width:70px;float:right;\"\r\n						 id=\"codeImg\"\r\n						title=\"\u70b9\u51fb\u5237\u65b0\"\r\n						onclick=\"refreshImg();\" />\r\n						<script>refreshImg();</script>\r\n						<div class=\"clear\"></div>\r\n					</td>\r\n				</tr> -->\r\n			</table>\r\n			<div class=\"login-btn\" onclick=\"login()\">\u767b&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u5f55</div>\r\n			<div class=\"login-btn\"  onclick=\"window.location='/portal/user!toRegister.action'\">\u6ce8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u518c</div>\r\n		</form>\r\n	</div>\r\n</body>\r\n</html>\r\n".toCharArray();
  }
}
