/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._mine;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _circle_0build_0circle__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    if (_caucho_expr_3.evalBoolean(_jsp_env)) {
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_5.evalBoolean(_jsp_env)) {
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _caucho_expr_1.print(out, _jsp_env, false);
        out.write(_jsp_string11, 0, _jsp_string11.length);
        _caucho_expr_6.print(out, _jsp_env, false);
        out.write(_jsp_string12, 0, _jsp_string12.length);
      }
      out.write(_jsp_string13, 0, _jsp_string13.length);
      if (_caucho_expr_7.evalBoolean(_jsp_env)) {
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _caucho_expr_1.print(out, _jsp_env, false);
        out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string17, 0, _jsp_string17.length);
    _caucho_expr_8.print(out, _jsp_env, false);
    out.write(_jsp_string18, 0, _jsp_string18.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string19, 0, _jsp_string19.length);
    if (_caucho_expr_3.evalBoolean(_jsp_env)) {
      out.write(_jsp_string20, 0, _jsp_string20.length);
    }
    out.write(_jsp_string21, 0, _jsp_string21.length);
    if (_caucho_expr_9.evalBoolean(_jsp_env)) {
      out.write(_jsp_string22, 0, _jsp_string22.length);
    }
    out.write(_jsp_string23, 0, _jsp_string23.length);
    _caucho_expr_10.print(out, _jsp_env, false);
    out.write(_jsp_string24, 0, _jsp_string24.length);
    _caucho_expr_11.print(out, _jsp_env, false);
    out.write(_jsp_string25, 0, _jsp_string25.length);
    _caucho_expr_12.print(out, _jsp_env, false);
    out.write(_jsp_string26, 0, _jsp_string26.length);
    _caucho_expr_13.print(out, _jsp_env, false);
    out.write(_jsp_string27, 0, _jsp_string27.length);
    _caucho_expr_14.print(out, _jsp_env, false);
    out.write(_jsp_string28, 0, _jsp_string28.length);
    _caucho_expr_15.print(out, _jsp_env, false);
    out.write(_jsp_string29, 0, _jsp_string29.length);
    _caucho_expr_16.print(out, _jsp_env, false);
    out.write(_jsp_string30, 0, _jsp_string30.length);
    _caucho_expr_17.print(out, _jsp_env, false);
    out.write(_jsp_string31, 0, _jsp_string31.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/mine/circle_build_circle.jsp"), -5712864974319949715L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${method eq 'update' }");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.id }");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${!empty(cover) }");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.cover}");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${empty(cover) }");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${method }");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${method ne 'update' }");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.name }");
      _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==1?\"checked\":\"\" }");
      _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==2?\"checked\":\"\" }");
      _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==3?\"checked\":\"\" }");
      _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==4?\"checked\":\"\" }");
      _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==5?\"checked\":\"\" }");
      _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.type==6?\"checked\":\"\" }");
      _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${circle.describetion }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;

  private final static char []_jsp_string16;
  private final static char []_jsp_string2;
  private final static char []_jsp_string21;
  private final static char []_jsp_string6;
  private final static char []_jsp_string27;
  private final static char []_jsp_string14;
  private final static char []_jsp_string24;
  private final static char []_jsp_string30;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string20;
  private final static char []_jsp_string7;
  private final static char []_jsp_string26;
  private final static char []_jsp_string15;
  private final static char []_jsp_string0;
  private final static char []_jsp_string31;
  private final static char []_jsp_string8;
  private final static char []_jsp_string28;
  private final static char []_jsp_string29;
  private final static char []_jsp_string23;
  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string17;
  private final static char []_jsp_string13;
  private final static char []_jsp_string18;
  private final static char []_jsp_string1;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string22;
  private final static char []_jsp_string11;
  private final static char []_jsp_string9;
  private final static char []_jsp_string25;
  static {
    _jsp_string16 = "\r\n		<form action=\"".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n	<head>\r\n		<title>\u521b\u5efa\u5708\u5b50</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;\">\r\n		<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n		<meta name=\"format-detection\" content=\"telephone=no\">\r\n		<link href=\"".toCharArray();
    _jsp_string21 = "\r\n			".toCharArray();
    _jsp_string6 = "/mine/circle!myCircle.action\";\r\n				});\r\n		</script>\r\n	</head>\r\n	<body style=\"background-color:#F0EFEE;margin-bottom:90px;\">\r\n		".toCharArray();
    _jsp_string27 = "/>\r\n				<label for=\"hobby\">\u5174\u8da3\u7231\u597d</label>\r\n				<input type=\"radio\" name=\"circle.type\" value=\"4\" id=\"p\" ".toCharArray();
    _jsp_string14 = "/images/circle-cover.jpg\" alt=\"\" />\r\n				".toCharArray();
    _jsp_string24 = "\" class=\"circle-name\"/>\r\n			</div>\r\n			<div class=\"circle-type-box\">\r\n				<input type=\"radio\" name=\"circle.type\" value=\"1\" id=\"city\" ".toCharArray();
    _jsp_string30 = "/>\r\n				<label for=\"family\">\u5bb6\u65cf</label>\r\n			</div>\r\n			<div class=\"circle-introduction-box\">\r\n				<div >\u5708\u5b50\u4ecb\u7ecd</div>\r\n				<textarea  s name=\"circle.describetion\">".toCharArray();
    _jsp_string10 = "\r\n					<img src=\"".toCharArray();
    _jsp_string5 = "/phone-js/xback.js\"></script>\r\n		<script type=\"text/javascript\">\r\n			function submitForm(){\r\n				if($(\"#title\").val()==\"\"){\r\n					alert(\"\u8bf7\u586b\u5199\u5708\u5b50\u540d\u79f0\");\r\n				}else {\r\n					$(\"#myForm\").submit();\r\n				}\r\n			}\r\n			XBack.listen(function(){\r\n				  window.location = \"".toCharArray();
    _jsp_string20 = "\r\n				<div class=\"circle-update-box\">\r\n			".toCharArray();
    _jsp_string7 = "\r\n			<div class=\"circle-cover-box\" onclick=\"window.location='".toCharArray();
    _jsp_string26 = "/>\r\n				<label for=\"classmate\">\u540c\u5b66</label>\r\n				<input type=\"radio\" name=\"circle.type\" value=\"3\" checked=\"checked\" id=\"hobby\" ".toCharArray();
    _jsp_string15 = "\r\n				<p style=\"font-size:10px;\">\u70b9\u51fb\u56fe\u7247\u66f4\u6362\u5c01\u9762</p>\r\n			</div>\r\n		".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string31 = "</textarea>\r\n			</div>\r\n		</form>\r\n			<div class=\"circle-build-sub\" onclick=\"submitForm()\">\u4fdd\u5b58</div>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string8 = "/mine/circle!setCover.action?circle.id=".toCharArray();
    _jsp_string28 = "/>\r\n				<label for=\"p\">\u5bb6\u957f\u4f1a</label>\r\n				<input type=\"radio\" name=\"circle.type\" value=\"5\" id=\"friend\"  ".toCharArray();
    _jsp_string29 = "/>\r\n				<label for=\"friend\">\u597d\u53cb</label>\r\n				<input type=\"radio\" name=\"circle.type\" value=\"6\" id=\"family\" ".toCharArray();
    _jsp_string23 = "\r\n				<input type=\"text\" placeholder=\"\u5708\u5b50\u540d\u79f0\"  name=\"circle.name\" id=\"title\" value=\"".toCharArray();
    _jsp_string4 = "/js/jquery.js\"></script>\r\n		<script type=\"text/javascript\"  src=\"".toCharArray();
    _jsp_string19 = "\"/>\r\n			".toCharArray();
    _jsp_string17 = "/mine/circle!".toCharArray();
    _jsp_string13 = "\r\n				".toCharArray();
    _jsp_string18 = ".action\" id=\"myForm\" method=\"post\" >\r\n			<input  type=\"hidden\" id=\"circleId\" name=\"circle.id\" value=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string12 = "\" alt=\"\" />\r\n				".toCharArray();
    _jsp_string3 = "/phone-css/phone.css\" rel='stylesheet' type='text/css' />\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string22 = "\r\n				<div class=\"circle-build-box\">\r\n			".toCharArray();
    _jsp_string11 = "/circle_cover/".toCharArray();
    _jsp_string9 = "&method=update'\">\r\n				".toCharArray();
    _jsp_string25 = "/>\r\n				<label for=\"city\">\u540c\u57ce</label>\r\n				<input type=\"radio\" name=\"circle.type\" value=\"2\" id=\"classmate\" ".toCharArray();
  }
}
