/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._mine;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _follow_0list__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string11, 0, _jsp_string11.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    _caucho_expr_5.print(out, _jsp_env, false);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    _caucho_expr_6.print(out, _jsp_env, false);
    out.write(_jsp_string14, 0, _jsp_string14.length);
    _caucho_expr_7.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_8.print(out, _jsp_env, false);
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string17, 0, _jsp_string17.length);
    _caucho_expr_9.print(out, _jsp_env, false);
    out.write(_jsp_string18, 0, _jsp_string18.length);
    _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_2 = _caucho_expr_10.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
    _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
    while (_jsp_iter_2.hasNext()) {
      Object _jsp_i_2 = _jsp_iter_2.next();
      _jsp_loop_1.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
      pageContext.setAttribute("u", _jsp_i_2);
      out.write(_jsp_string19, 0, _jsp_string19.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string20, 0, _jsp_string20.length);
      _caucho_expr_11.print(out, _jsp_env, false);
      out.write(_jsp_string21, 0, _jsp_string21.length);
      _caucho_expr_12.print(out, _jsp_env, false);
      out.write(_jsp_string22, 0, _jsp_string22.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string23, 0, _jsp_string23.length);
      _caucho_expr_13.print(out, _jsp_env, false);
      out.write('/');
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string24, 0, _jsp_string24.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string25, 0, _jsp_string25.length);
      _caucho_expr_15.print(out, _jsp_env, false);
      out.write(_jsp_string26, 0, _jsp_string26.length);
      _caucho_expr_16.print(out, _jsp_env, false);
      out.write(_jsp_string27, 0, _jsp_string27.length);
      _caucho_expr_17.print(out, _jsp_env, false);
      out.write(_jsp_string28, 0, _jsp_string28.length);
      _caucho_expr_15.print(out, _jsp_env, false);
      out.write(_jsp_string29, 0, _jsp_string29.length);
    }
    pageContext.pageSetOrRemove("u", null);
    out.write(_jsp_string30, 0, _jsp_string30.length);
    _caucho_expr_6.print(out, _jsp_env, false);
    out.write(_jsp_string31, 0, _jsp_string31.length);
    _caucho_expr_6.print(out, _jsp_env, false);
    out.write(_jsp_string32, 0, _jsp_string32.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/mine/follow_list.jsp"), 3353527430213949589L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1;

    final com.caucho.jsp.IteratorLoopSupportTag get_jsp_loop_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_loop_1 == null) {
        _jsp_loop_1 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_loop_1;
    }

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${appId}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${timestamp}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${noncestr}");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${signature}");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${isLogin }");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${lastIdSign }");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${nickname }");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${follows }");
      _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.uid }");
      _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.fid }");
      _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.uid}");
      _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.head_img}");
      _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.nickname }");
      _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.introduction }");
      _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${u.fid}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;

  private final static char []_jsp_string26;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string23;
  private final static char []_jsp_string3;
  private final static char []_jsp_string20;
  private final static char []_jsp_string15;
  private final static char []_jsp_string17;
  private final static char []_jsp_string27;
  private final static char []_jsp_string2;
  private final static char []_jsp_string24;
  private final static char []_jsp_string10;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string22;
  private final static char []_jsp_string25;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string29;
  private final static char []_jsp_string30;
  private final static char []_jsp_string19;
  private final static char []_jsp_string31;
  private final static char []_jsp_string16;
  private final static char []_jsp_string11;
  private final static char []_jsp_string28;
  private final static char []_jsp_string12;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string21;
  private final static char []_jsp_string32;
  private final static char []_jsp_string13;
  private final static char []_jsp_string8;
  static {
    _jsp_string26 = "</p>\r\n								<p class=\"introduction-p\">".toCharArray();
    _jsp_string18 = "\" \r\n						class=\"nickname-input\"/>\r\n					<input type=\"button\" onclick=\"submitForm()\" class=\"nickname-sub\"/>\r\n			</div>\r\n		</form>\r\n			<div id=\"wrapper\" class=\"circle-user-box\" >\r\n			<ul id=\"ulId\" >\r\n				".toCharArray();
    _jsp_string4 = "/phone-css/reset.css\" />\r\n		<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string9 = "/phone-js/xback.js\"></script>\r\n		<script type=\"text/javascript\" src=\"http://res.wx.qq.com/open/js/jweixin-1.2.0.js\"></script>\r\n		<script type=\"text/javascript\">\r\n			function submitForm(){\r\n				$('#searchForm').submit();\r\n			}\r\n			wx.config({\r\n				 debug: false, // \u5f00\u542f\u8c03\u8bd5\u6a21\u5f0f,\u8c03\u7528\u7684\u6240\u6709api\u7684\u8fd4\u56de\u503c\u4f1a\u5728\u5ba2\u6237\u7aefalert\u51fa\u6765\uff0c\u82e5\u8981\u67e5\u770b\u4f20\u5165\u7684\u53c2\u6570\uff0c\u53ef\u4ee5\u5728pc\u7aef\u6253\u5f00\uff0c\u53c2\u6570\u4fe1\u606f\u4f1a\u901a\u8fc7log\u6253\u51fa\uff0c\u4ec5\u5728pc\u7aef\u65f6\u624d\u4f1a\u6253\u5370\u3002\r\n	             appId: '".toCharArray();
    _jsp_string23 = "/uploadImages/growthLog".toCharArray();
    _jsp_string3 = "/phone-css/phone.css\" rel='stylesheet' type='text/css' />\r\n		<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string20 = "/mine/member!detailForFollow.action?user.id=".toCharArray();
    _jsp_string15 = "\"/>\r\n		<input type=\"hidden\" id=\"lastIdSign\" value=\"".toCharArray();
    _jsp_string17 = "/mine/follow!list.action\" method=\"post\" id=\"searchForm\">\r\n			<div class=\"search-nickname-div\">\r\n					<input type=\"text\" name=\"user.nickname\" id=\"nickname\" value=\"".toCharArray();
    _jsp_string27 = "</p>\r\n							</div>\r\n						</div>\r\n						<div class=\"follow-div\" onclick=\"cancleFollow(".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n	<head>\r\n		<title>\u6210\u957f\u65e5\u5fd7</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;\">\r\n		<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n		<meta name=\"format-detection\" content=\"telephone=no\">\r\n		<link href=\"".toCharArray();
    _jsp_string24 = "\" \r\n								onerror=\"this.src='".toCharArray();
    _jsp_string10 = "', // \u5fc5\u586b\uff0c\u516c\u4f17\u53f7\u7684\u552f\u4e00\u6807\u8bc6\r\n	             timestamp: '".toCharArray();
    _jsp_string6 = "/js/jquery.js\"></script>\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string7 = "/phone-js/iscroll.js\"></script>\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string22 = "'\">\r\n							<div class=\"head-img-div\">\r\n								<img src=\"".toCharArray();
    _jsp_string25 = "/images/default_head.png'\"  width=\"100%\" alt=\"\" />\r\n							</div>\r\n							<div class=\"user-info-div\">\r\n								<p>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string14 = "/mine/follow!cancleFollow.action\",{\"follow.id\":followId},function(data){\r\n						if(data == 1){\r\n							item.parent(\"li\").remove();\r\n						}\r\n					});\r\n				}\r\n			}\r\n			XBack.listen(function(){\r\n		 		wx.closeWindow();\r\n			});\r\n			\r\n		</script>\r\n	</head>\r\n	<body style=\"background-color:#F0EFEE;\" onload=\"ifLogin()\">\r\n		<input type=\"hidden\" id=\"isLogin\" value=\"".toCharArray();
    _jsp_string29 = "',$(this))\">\r\n							<p>\u53d6\u6d88\u5173\u6ce8</p>\r\n						</div>\r\n						<div class=\"clear\"></div>\r\n					</li>\r\n				".toCharArray();
    _jsp_string30 = "\r\n			</ul>\r\n		</div>\r\n		<script type=\"text/javascript\">\r\n				var loadDatas = \"\";\r\n				function loadData(){\r\n					var	lastIdSign = $(\"#lastIdSign\").val();\r\n					var nickname = $(\"#nickname\").val();\r\n					 $.ajax({ \r\n						 type: \"post\", \r\n						 url: \"follow!loadData.action\", \r\n						 async: false,\r\n						 dataType: \"json\", \r\n						 data:{\"lastIdSign\":lastIdSign,\"user.nickname\":nickname},\r\n						 success: function (data) {\r\n							 if(data == \"-1\"){\r\n								 alert(\"\u53c2\u6570\u9519\u8bef\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u91cd\u8bd5\");\r\n							 }else if(data == \"0\"){\r\n								 loadDatas = \"\";\r\n							 }else{\r\n								 loadDatas = data;\r\n							 }\r\n						 } \r\n						});\r\n				}\r\n				refresher.init({\r\n					id: \"wrapper\",//<------------------------------------------------------------------------------------\u2510\r\n					pullDownAction: Refresh,\r\n					pullUpAction: Load\r\n				});\r\n				var generatedCount = 0;\r\n				function Refresh() {\r\n					var nickname = $(\"#nickname\").val();\r\n					window.location = '".toCharArray();
    _jsp_string19 = "\r\n					<li >\r\n						<div onclick=\"window.location='".toCharArray();
    _jsp_string31 = "/mine/follow!list.action?user.nickname='+nickname;\r\n				}\r\n				\r\n				function Load() {\r\n					loadData();\r\n					setTimeout(function () {// <-- Simulate network congestion, remove setTimeout from production!\r\n						var el, li, i;\r\n						el = document.querySelector(\"#wrapper ul\");\r\n						if(loadDatas != ''){\r\n							$.each(loadDatas,function(i,item){\r\n								li = document.createElement('li');\r\n								 var innerH = \"\"\r\n								innerH = '<div onclick=\"window.location=\\'".toCharArray();
    _jsp_string16 = "\"/>\r\n		<form action=\"".toCharArray();
    _jsp_string11 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u65f6\u95f4\u6233\r\n	             nonceStr: '".toCharArray();
    _jsp_string28 = ",'".toCharArray();
    _jsp_string12 = "', // \u5fc5\u586b\uff0c\u751f\u6210\u7b7e\u540d\u7684\u968f\u673a\u4e32\r\n	             signature:'".toCharArray();
    _jsp_string5 = "/phone-css/pullToRefresh.css\" />\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string21 = "&followId=".toCharArray();
    _jsp_string32 = "/mine/member!detailForCircle.action?user.id='+item.uid+'\\'\">'\r\n											 +'<div class=\"head-img-div\">'\r\n												 	+'<img src=\"/uploadImages/growthLog'+item.uid+'/'+item.head_img+'\" '\r\n													+'onerror=\"this.src=\\'/images/default_head.png\\'\"  width=\"100%\" />'\r\n										     +'</div>'\r\n										     +'<div class=\"user-info-div\">'\r\n													+'<p>'+item.nickname+'</p>'\r\n													+'<p class=\"introduction-p\">'+item.introduction+'</p>'\r\n											 +'</div>'\r\n										  +'</div>'\r\n										  +'<div class=\"follow-div\" onclick=\"cancleFollow('+item.fid+',\\''+item.nickname+'\\',$(this))\">'\r\n									 	   		+'<p >\u53d6\u6d88\u5173\u6ce8</p>'\r\n									  	  + '</div>'\r\n									  	  +'<div class=\"clear\"></div>'; \r\n								li.innerHTML = innerH;\r\n								if(i == loadDatas.length-1){\r\n									var lastIdSignNode = document.getElementById('lastIdSign');\r\n									lastIdSignNode.value = item.fid;\r\n								}\r\n								el.appendChild(li, el.childNodes[0]);\r\n				    		});\r\n						}\r\n						wrapper.refresh();\r\n						for (var i = 0; i < document.querySelectorAll(\"#wrapper ul li\").length; i++) {\r\n							document.querySelectorAll(\"#wrapper ul li\")[i];\r\n						}\r\n						loadDatas = '';\r\n					}, 1000);\r\n				}\r\n				\r\n		</script>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string13 = "',// \u5fc5\u586b\uff0c\u7b7e\u540d\uff0c\u89c1\u9644\u5f551\r\n				      jsApiList: [\r\n				                  'checkJsApi',\r\n				                  'closeWindow'\r\n				                 ] // \u5fc5\u586b\uff0c\u9700\u8981\u4f7f\u7528\u7684JS\u63a5\u53e3\u5217\u8868\uff0c\u6240\u6709JS\u63a5\u53e3\u5217\u8868\u89c1\u9644\u5f552\r\n				      });\r\n			function ifLogin(){\r\n				  var isLogin = $(\"#isLogin\").val();\r\n				   if(isLogin != \"\"&&isLogin==\"no\"){\r\n					  alert(\"\u8bf7\u5148\u767b\u5f55\u54e6\");\r\n					  wx.closeWindow();\r\n				  } \r\n			  }\r\n			function cancleFollow(followId,nickname,item){\r\n				if(confirm(\"\u60a8\u786e\u5b9a\u4e0d\u518d\u5173\u6ce8\"+nickname+\"\u5417\")){\r\n					$.post(\"".toCharArray();
    _jsp_string8 = "/phone-js/pullToRefresh.js\"></script>\r\n		<script type=\"text/javascript\"  src=\"".toCharArray();
  }
}
