/*
 * JSP generated by Resin Professional 4.0.54 (built Tue, 03 Oct 2017 01:42:53 PDT)
 */

package _jsp._web_22dinf._content._mine;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _integral_0award_0evaluation_0iphone__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.defaultSetOrRemove("cache_time", "86400");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("cache_scope", "application");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.defaultSetOrRemove("base", _caucho_expr_0.evalObject(_jsp_env));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string11, 0, _jsp_string11.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string14, 0, _jsp_string14.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string17, 0, _jsp_string17.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string18, 0, _jsp_string18.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string19, 0, _jsp_string19.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string20, 0, _jsp_string20.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string21, 0, _jsp_string21.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string22, 0, _jsp_string22.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2496007962829123395L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/mine/integral_award_evaluation_iphone.jsp"), -3811485285563126088L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/content/common/taglib.jsp"), 3690004229260259696L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "s", "/struts-tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "g", "/WEB-INF/czrz-taglib.tld");
      manager.addTaglibFunctions(_jsp_functionMap, "cache", "http://www.opensymphony.com/oscache");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${awardRecord.id }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;

  private final static char []_jsp_string5;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string15;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string21;
  private final static char []_jsp_string4;
  private final static char []_jsp_string18;
  private final static char []_jsp_string7;
  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string22;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string20;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string19;
  private final static char []_jsp_string10;
  static {
    _jsp_string5 = "/phone-css/demo.css\">\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string8 = "/phone-js/xback.js\"></script>\r\n		<script src=\"".toCharArray();
    _jsp_string12 = "/js/extend-webuploader-phone.js\" type=\"text/javascript\"></script>\r\n          <script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string15 = "/uploadImages',\r\n		            //\u5f53\u5ba2\u6237\u7aef\u539f\u6709\u6587\u4ef6\u5220\u9664\u65f6\u7684\u540e\u53f0\u5904\u7406\u5730\u5740\uff0c\u5fc5\u586b\r\n		            removeUrl: '".toCharArray();
    _jsp_string11 = "/js/webuploader.js\"></script>\r\n         <script src=\"".toCharArray();
    _jsp_string16 = "/uploadImages',\r\n		            //\u521d\u59cb\u5316\u5ba2\u6237\u7aef\u4e0a\u4f20\u6587\u4ef6\uff0c\u4ece\u540e\u53f0\u83b7\u53d6\u6587\u4ef6\u7684\u5730\u5740, \u53ef\u9009\uff0c\u5f53\u6b64\u53c2\u6570\u4e3a\u7a7a\u65f6\uff0c\u9ed8\u8ba4\u5df2\u4e0a\u4f20\u7684\u6587\u4ef6\u4e3a\u7a7a\r\n		            initUrl: '".toCharArray();
    _jsp_string21 = "/images/smile_face.png\"  />\r\n			</p>\r\n			<p>\r\n				\u4e3a\u5956\u54c1\u586b\u5199\u8bc4\u4ef7\uff0c\u8ddf\u5c0f\u4f19\u4f34\u4eec\u5206\u4eab\u9886\u53d6\u5956\u54c1\u7684\u559c\u60a6\u5427\uff0c\u63d0\u4ea4\u8bc4\u4ef7\u8fd8\u53ef\u83b7\u5f9710\u79ef\u5206\u54e6\r\n			</p>\r\n		</div>\r\n		<form action=\"integral!saveEvaluation.action\" method=\"post\" id=\"myForm\">\r\n		<input type=\"hidden\" value=\"".toCharArray();
    _jsp_string4 = "/css/bootstrap-theme.min.css\">\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string18 = "/mine/integral!savePhotos.action\",  \r\n							        data: {\"myImgs\" : JSON.stringify(imgDatas),\"awardRecord.id\":awardRecordId},  \r\n							        async: true,  \r\n							        cache: false,\r\n							        success: function (data) { \r\n							              if(data>0) {\r\n							            	  $(\"#myForm\").submit();  \r\n							              }\r\n							        },  \r\n									error: function(data) {  \r\n							              alert(e.responseText); //alert\u9519\u8bef\u4fe1\u606f   \r\n							       }  \r\n							   }); \r\n		        		} else{\r\n		        			$(\"#myForm\").submit(); \r\n		        		}\r\n		        	}\r\n		        }\r\n			 XBack.listen(function(){\r\n				  window.location = \"".toCharArray();
    _jsp_string7 = "/js/jquery-1.10.2.js\"></script>\r\n		<script type=\"text/javascript\"  src=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "/js/jquery.blockUI.js\"></script>\r\n		<style type=\"text/css\">\r\n        	.myPhotos{\r\n				width:95%;\r\n				margin:0 auto;\r\n				margin-top:10px;\r\n			}\r\n			.myPhotos .photo{\r\n				width:26%;\r\n				float:left;\r\n				margin-left:4.5%;\r\n				margin-top:8px;\r\n				position:relative;\r\n			}\r\n			.myPhotos .photo img{\r\n				height:80px;\r\n				width:100%;\r\n			}\r\n			.myPhotos .photo .deletePhoto{\r\n				width:100%;\r\n				height:20px;\r\n				background:url(../images/delete-photo-bg.png);\r\n				position:absolute;\r\n				top:0px;\r\n				text-align:right;\r\n			}\r\n			.myPhotos .photo .deletePhoto p{\r\n				width:15px;\r\n				height:15px;\r\n				background:url(../images/delete-photo.png);\r\n			}\r\n        </style>\r\n		<script type=\"text/javascript\">\r\n		 	window.webuploader = {\r\n		            config:{\r\n		                thumbWidth:100, //\u7f29\u7565\u56fe\u5bbd\u5ea6\uff0c\u53ef\u7701\u7565\uff0c\u9ed8\u8ba4\u4e3a110\r\n		                thumbHeight: 100, //\u7f29\u7565\u56fe\u9ad8\u5ea6\uff0c\u53ef\u7701\u7565\uff0c\u9ed8\u8ba4\u4e3a110\r\n		                wrapId: 'uploader', //\u5fc5\u586b\r\n		                theAgent:'phone',\r\n		            },\r\n		            //\u5904\u7406\u5ba2\u6237\u7aef\u65b0\u6587\u4ef6\u4e0a\u4f20\u65f6\uff0c\u9700\u8981\u8c03\u7528\u540e\u53f0\u5904\u7406\u7684\u5730\u5740, \u5fc5\u586b\r\n		            uploadUrl: '".toCharArray();
    _jsp_string17 = "/uploadImages',\r\n		        }\r\n		        var imgNum = 1;\r\n		        var fileCount = 0;\r\n		        function deletePhoto(item){\r\n		        	var itemId = item.parent().attr(\"id\");\r\n		        	var photoNum = parseInt(itemId.substring(8));\r\n		        	var photoCount = $(\".photo\").length;\r\n		        	if(photoNum < photoCount){\r\n		        		var afterNum = photoNum+1;\r\n		        		for(var v=afterNum;v<=photoCount;v++){\r\n		        			var num = v-1;\r\n		        			$(\"#myImage_\"+v).attr(\"id\",\"myImage_\"+num);\r\n		        		}\r\n		        	}\r\n		        	$(\"#myImage_\"+photoNum).remove();\r\n		        	imgNum = imgNum -1;\r\n		        	fileCount = fileCount-1;\r\n		        	$(\"#fileAcount\").html(fileCount );\r\n		        }\r\n		        function subEvaluation(){\r\n		        	var imgDatas = new Array();\r\n		        	var awardRecordId = $(\"#awardRecordId\").val();\r\n		        	var arEvaluation = $(\"#arEvaluation\").val();\r\n		        	if(arEvaluation==\"\"||arEvaluation==null){\r\n		        		alert(\"\u4eb2\uff0c\u4f60\u8fd8\u6ca1\u6709\u586b\u5199\u8bc4\u4ef7\u54e6\");\r\n		        	}else{\r\n		        		$.blockUI({ \r\n	    					message: $('#submitMess'),\r\n	    					css: {border:'#666666',width:'0px',height:'0px',top:'50%',left:'50%' } \r\n	    					});\r\n		        		if(imgNum > 0) {\r\n		        			for(var i=imgNum;i>0;i--){\r\n		        				if($(\"#myImage_\"+i).length>0) {\r\n		        						if($(\"#myImage_\"+i)) {\r\n		        							imgDatas[i-1] = $(\"#myImage_\"+i+\" img\").eq(0).attr(\"src\");\r\n		        							//imgDatas[i-1] = photo.attr(\"src\");\r\n		        						}\r\n		        				}\r\n							}\r\n		        			 $.ajax({  \r\n							        type: \"post\",         \r\n							        url:\"".toCharArray();
    _jsp_string22 = "\" id=\"awardRecordId\" name=\"awardRecord.id\"/>\r\n		<div class=\"evaluation-box\">\r\n			<p>\u8bc4\u4ef7\uff1a</p>\r\n			<p class=\"evaluation-area\">\r\n				<textarea   name=\"awardRecord.evaluation\" id=\"arEvaluation\"></textarea>\r\n			</p>\r\n		</div>\r\n		</form>\r\n		<div id=\"myPhotos\" class=\"myPhotos\" >\r\n				<div class=\"clear\" id=\"clearDiv\"></div>\r\n		</div>\r\n		<div class=\"page-container\" style=\"margin-top:20px;width:95%;margin-left:2.5%;background-color:#fff;padding: 10px 0;\">\r\n	        <div id=\"uploader\" class=\"wu-example\">\r\n	            <div class=\"queueList\">\r\n	                 <div id=\"dndArea\" class=\"placeholder\">\r\n	                      <div id=\"filePicker\"></div>\r\n	                 </div>\r\n	            </div>\r\n	            <div class=\"statusBar\" style=\"display:none\">\r\n	                 <div class=\"progress\">\r\n	                      <span class=\"text\">0%</span>\r\n	                      <span class=\"percentage\"></span>\r\n	                 </div>    \r\n	                 <div class=\"info\"></div>\r\n	                 <div class=\"btns\">\r\n	                      <div id=\"filePicker2\"></div>\r\n	                 </div>\r\n	            </div>\r\n	         </div>\r\n	    </div>\r\n	    <div class=\"evaluation-sub-box\" onclick=\"subEvaluation()\">\r\n	    	\u63d0&nbsp;&nbsp;&nbsp;&nbsp;\u4ea4\r\n	    </div>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string6 = "/css/webuploader.css\">\r\n		<script src=\"".toCharArray();
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n	<head>\r\n		<title>\u586b\u5199\u8bc4\u4ef7</title>\r\n		<meta name=\"keywords\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"description\" value=\"\u9996\u4e2a\u8bb0\u5f55\u6210\u957f\u65e5\u5fd7\u7684\u7f51\u7ad9\" />\r\n		<meta name=\"author\" value=\"\u6210\u957f\u65e5\u5fd7\" />\r\n		<meta name=\"viewport\" content=\"width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;\">\r\n		<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n		<meta name=\"format-detection\" content=\"telephone=no\">\r\n		<link href=\"".toCharArray();
    _jsp_string14 = "/member/diary!upload.action',\r\n		            //\u5904\u7406\u5ba2\u6237\u7aef\u539f\u6709\u6587\u4ef6\u66f4\u65b0\u65f6\u7684\u540e\u53f0\u5904\u7406\u5730\u5740\uff0c\u5fc5\u586b\r\n		            updateUrl: '".toCharArray();
    _jsp_string20 = "/images/submitMess.png\" style=\"width:315px;height:332px;\" alt=\"\" />\r\n		</div>\r\n		<div class=\"welcome-box\">\r\n			<p>\r\n				<img src=\"".toCharArray();
    _jsp_string3 = "/phone-css/phone.css\" rel='stylesheet' type='text/css' />\r\n		<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string9 = "/js/exif.js\"></script>\r\n        <script src=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string19 = "/mine/integral!claimRecord.action\";\r\n				});\r\n		</script>\r\n	</head>\r\n	<body style=\"background-color:#F0EFEE;\">\r\n		<div id=\"submitMess\" class=\"block-box\">\r\n			<img src=\"".toCharArray();
    _jsp_string10 = "/js/json2.js\"></script>\r\n        <script type=\"text/javascript\" src=\"".toCharArray();
  }
}
